apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calcard.fullname" . }}-secret
  labels:
    {{- include "calcard.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_OAUTH_CLIENT_SECRET: {{ .Values.app.oauth.clientSecret | quote }}
  APP_SESSION_SECRET: {{ .Values.app.sessionSecret | quote }}
  {{- if .Values.postgres.enabled }}
  {{- $dbHost := include "calcard.postgresHost" . -}}
  APP_DB_DSN: {{ printf "postgres://%s:%s@%s:%d/%s?sslmode=%s" .Values.app.db.user .Values.app.db.password $dbHost .Values.app.db.port .Values.app.db.name .Values.app.db.sslmode | quote }}
  {{- else }}
  {{- $dbHost := required "app.db.host is required when postgres.enabled is false" .Values.app.db.host -}}
  APP_DB_DSN: {{ printf "postgres://%s:%s@%s:%d/%s?sslmode=%s" .Values.app.db.user .Values.app.db.password $dbHost .Values.app.db.port .Values.app.db.name .Values.app.db.sslmode | quote }}
  {{- end }}
