{{- $name := default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- $fullname := (default $name .Values.fullnameOverride) | trunc 63 | trimSuffix "-" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-secret
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  APP_OAUTH_CLIENT_SECRET: {{ .Values.app.oauth.clientSecret | quote }}
  {{- if not .Values.app.sessionSecretExistingSecret.name }}
  APP_SESSION_SECRET: {{ .Values.app.sessionSecret | quote }}
  {{- end }}
  {{- if and (not .Values.app.db.existingSecret.name) (not .Values.app.db.credentialsExistingSecret.name) }}
  {{- $dbHost := "" -}}
  {{- if .Values.postgres.enabled }}
  {{- if .Values.app.db.host -}}
  {{- $dbHost = .Values.app.db.host -}}
  {{- else -}}
  {{- $dbHost = printf "%s-postgres" $fullname -}}
  {{- end -}}
  {{- else -}}
  {{- $dbHost = required "app.db.host is required when postgres.enabled is false" .Values.app.db.host -}}
  {{- end -}}
  APP_DB_DSN: {{ printf "postgres://%s:%s@%s:%d/%s?sslmode=%s" .Values.app.db.user .Values.app.db.password $dbHost .Values.app.db.port .Values.app.db.name .Values.app.db.sslmode | quote }}
  {{- end }}
